### PR TITLE
FUN-170 Basic styling updates

### PR DESCRIPTION
**Pull request by nomadicoder**

### CODE REVIEW

**Comment by ebtoner** [comment]
I've attached uploaded files for the logo (slightly crisper image) and the favicon (which I generated myself and hopefully should work okay) to the Jira ticket for this.

**Comment by sensei100** [comment]
@nomadicoder Should I wait to review this one until the new logo and icon are added?

**Comment by nomadicoder** [comment]
@sensei100 Yes, let me work with the new logo and I"ll ping you when I'm done.

**Comment by ebtoner** [comment]
@nomadicoder The image files have already been resized to match what you already added and saved in the correct format, so it should just be matter of updating them in the directory. If you need anything adjusted, just let me know as I can quickly make those changes via photoshop.

**Comment by nomadicoder** [comment]
@sensei100 I've committed the updated favicon and logo. This PR is ready for review.

**Comment by sensei100** [comment]
@nomadicoder In reading through the feedback on the ticket, all the site links should be the darker blue color.  The start over button should also be changed to dark blue.  Both buttons should remain the darker blue color in the hover state as well.

**Comment by sensei100** [comment]
@nomadicoder There is still an issue with the pagination links at the bottom of the search results.
Screen Shot 2019-12-16 at 3 15 47 PM
The text color for the search icon and the Back to Search button on the individual record pages should be changed to white.
Screen Shot 2019-12-16 at 3 12 56 PM
Screen Shot 2019-12-16 at 3 17 12 PM

**Comment by sensei100** [comment]
@nomadicoder There is still an issue with the pagination links at the bottom of the search results.
Screen Shot 2019-12-16 at 3 15 47 PM

Also, the close icon is still grey.
Screen Shot 2019-12-16 at 3 12 56 PM

**Comment by sensei100** [comment]
@nomadicoder Your changes look good, but there are travis and circle ci issues now blocking me from merging it.

**Comment by cmharlow** [comment]
@nomadicoder pushed up rebase that only moved this work over to circleci setup. once green, feel free to proceed.

**Pull request merged**
